import pygame

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN = pygame.display.set_mode([SCREEN_WIDTH, SCREEN_HEIGHT])

ROLL_LEFT_BOUND = 0
ROLL_GRID_START = 200
ROLL_RIGHT_BOUND = SCREEN_WIDTH
ROLL_UP_BOUND = 100
ROLL_DOWN_BOUND = 700
ROLL_WIDTH = ROLL_RIGHT_BOUND - ROLL_LEFT_BOUND
ROLL_HEIGHT = ROLL_DOWN_BOUND - ROLL_UP_BOUND

OUTPUTS_LEFT_BOUND = 0
OUTPUTS_RIGHT_BOUND = SCREEN_WIDTH
OUTPUTS_UP_BOUND = ROLL_DOWN_BOUND
OUTPUTS_DOWN_BOUND = SCREEN_HEIGHT
OUTPUTS_WIDTH = OUTPUTS_RIGHT_BOUND - OUTPUTS_LEFT_BOUND
OUTPUTS_HEIGHT = OUTPUTS_DOWN_BOUND - OUTPUTS_UP_BOUND

TEMP_MUSIC_DIRECTORY = "temp_music"

INPUTS_LEFT_BOUND = 0
INPUTS_RIGHT_BOUND = SCREEN_WIDTH
INPUTS_UP_BOUND = 0
INPUTS_DOWN_BOUND = ROLL_UP_BOUND
INPUTS_WIDTH = INPUTS_RIGHT_BOUND - INPUTS_LEFT_BOUND
INPUTS_HEIGHT = INPUTS_DOWN_BOUND - INPUTS_UP_BOUND

DOUBLE_CLICK_TIME = 300
FPS = 60

BLACK = (0, 0, 0)
DARK_GREY = (64, 64, 64)
GREY = (128, 128, 128)
LIGHT_GREY = (192, 192, 192)
WHITE = (255, 255, 255)

GREEN = (0, 255, 0)
RED = (255, 0, 0)
LIGHT_BLUE = (0, 150, 255)
ORANGE = (255, 165, 0)
YELLOW = (255,255,153)
PINK = (255,192,203)

TICKS_IN_BEAT = 96

PITCHES = ['C', 'C#', 'D', 'D#', 'E', 'F',
           'F#', 'G', 'G#', 'A', 'A#', 'B']

pygame.font.init()
FONT = pygame.font.Font(None, 28) 
